# Generated by Django 5.2.7 on 2026-02-22 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_employee_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='position',
            field=models.CharField(choices=[('STAFF', 'พนักงาน')], default='STAFF', max_length=10, verbose_name='ตำแหน่ง'),
        ),
    ]
